import React from 'react';
import { AggregatedMetrics, DeclineCodeData, DimensionBreakdown, Insight, FilterState } from '@/types';
import { formatPercent, formatNumber, formatCurrency, formatDateRange } from '@/utils/formatters';
import { DECLINE_CODES, VALUE_LABELS } from '@/data/constants';

interface ReportGeneratorProps {
  isOpen: boolean;
  onClose: () => void;
  metrics: AggregatedMetrics;
  filters: FilterState;
  declineCodes: DeclineCodeData[];
  breakdowns: {
    cardBrand: DimensionBreakdown[];
    cardType: DimensionBreakdown[];
    tokenType: DimensionBreakdown[];
    threeDSStatus: DimensionBreakdown[];
  };
  insights: Insight[];
}

function buildMarkdown(props: Omit<ReportGeneratorProps, 'isOpen' | 'onClose'>): string {
  const { metrics, filters, declineCodes, breakdowns, insights } = props;
  const now = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  const sections: string[] = [];

  sections.push(`# AuthRate — Payment Authorization Analysis Report`);
  sections.push(`**Generated:** ${now}`);
  sections.push(`**Date Range:** ${formatDateRange(filters.dateRange.start, filters.dateRange.end)}`);

  const activeFilters = Object.entries(filters)
    .filter(([k, v]) => k !== 'dateRange' && (Array.isArray(v) ? v.length > 0 : v !== null))
    .map(([k, v]) => `${k}: ${JSON.stringify(v)}`);
  if (activeFilters.length > 0) {
    sections.push(`**Active Filters:** ${activeFilters.join(' | ')}`);
  }

  sections.push(`\n---\n`);

  // KPIs
  sections.push(`## Key Performance Indicators\n`);
  sections.push(`| Metric | Value |`);
  sections.push(`|--------|-------|`);
  sections.push(`| Auth Rate | **${formatPercent(metrics.authRate)}** |`);
  sections.push(`| Approved Transactions | ${formatNumber(metrics.approved)} |`);
  sections.push(`| Declined Transactions | ${formatNumber(metrics.declined)} |`);
  sections.push(`| Total Volume | ${formatCurrency(metrics.totalVolume)} |`);
  sections.push(`| Est. Decline Cost | ${formatCurrency(metrics.estimatedDeclineCost)} |`);
  sections.push(`| Avg. Transaction | ${formatCurrency(metrics.avgAmount)} |`);

  // Decline codes
  sections.push(`\n## Top Decline Codes\n`);
  sections.push(`| Code | Name | Count | % of Declines | Category | Est. Impact |`);
  sections.push(`|------|------|-------|---------------|----------|-------------|`);
  declineCodes.slice(0, 10).forEach((d) => {
    sections.push(`| ${d.code} | ${d.name} | ${formatNumber(d.count)} | ${formatPercent(d.percentage)} | ${d.category} | ${formatCurrency(d.estimatedImpact, true)} |`);
  });

  // Breakdowns
  sections.push(`\n## Auth Rate by Dimension\n`);

  const formatBreakdown = (title: string, data: DimensionBreakdown[]) => {
    const lines = [`### ${title}\n`];
    lines.push(`| Segment | Auth Rate | Total | Declined |`);
    lines.push(`|---------|-----------|-------|----------|`);
    data.slice(0, 6).forEach((d) => {
      lines.push(`| ${VALUE_LABELS[d.label] ?? d.label} | ${formatPercent(d.authRate)} | ${formatNumber(d.total)} | ${formatNumber(d.declined)} |`);
    });
    return lines.join('\n');
  };

  sections.push(formatBreakdown('Card Brand', breakdowns.cardBrand));
  sections.push(formatBreakdown('Card Type', breakdowns.cardType));
  sections.push(formatBreakdown('Token Type', breakdowns.tokenType));
  sections.push(formatBreakdown('3DS Status', breakdowns.threeDSStatus));

  // Insights
  if (insights.length > 0) {
    sections.push(`\n## AI Insights\n`);
    insights.forEach((ins, i) => {
      sections.push(`### ${i + 1}. ${ins.title}`);
      sections.push(`**Category:** ${ins.category} | **Confidence:** ${ins.confidence}`);
      sections.push(`\n${ins.description}\n`);
      sections.push(`- **Current:** ${ins.currentMetric}`);
      sections.push(`- **Projected:** ${ins.projectedMetric}`);
      sections.push(`- **Est. Impact:** ${ins.estimatedImpact}`);
      sections.push(`- **Action:** ${ins.action}`);
      sections.push(`- **Supporting Data:** ${ins.supportingData}\n`);
    });
  }

  sections.push(`\n---\n*Report generated by AuthRate · Powered by Anthropic Claude*`);

  return sections.join('\n');
}

export default function ReportGenerator({ isOpen, onClose, ...props }: ReportGeneratorProps) {
  if (!isOpen) return null;

  const markdown = buildMarkdown(props);

  const handleCopy = () => {
    navigator.clipboard.writeText(markdown);
  };

  const handleDownload = () => {
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `authrate-report-${new Date().toISOString().split('T')[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60" onClick={onClose}>
      <div
        className="bg-[#0D1320] border border-gray-700 rounded-xl w-[700px] max-h-[80vh] flex flex-col shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-800">
          <span className="font-semibold text-white">Export Report</span>
          <button onClick={onClose} className="text-gray-500 hover:text-white text-lg">×</button>
        </div>

        <div className="flex-1 overflow-auto">
          <pre className="p-4 text-xs text-gray-300 font-mono whitespace-pre-wrap leading-relaxed">
            {markdown}
          </pre>
        </div>

        <div className="px-5 py-4 border-t border-gray-800 flex gap-2 justify-end">
          <button onClick={handleCopy} className="btn-secondary text-sm">Copy to Clipboard</button>
          <button onClick={handleDownload} className="btn-primary text-sm">Download .md</button>
        </div>
      </div>
    </div>
  );
}
